### ISSUE TITLE
the noise level of the pretrained denoise model

### ISSUE THREAD

**Issue by jiangzidong** [anchen1011/toflow#12]
Hi @anchen1011 thanks for your sharing the pretrained model, the denoising effect is very impressive!

I want to train the denoise model based on my own dataset.
I noticed that there is a file `add_noise_to_input` to generate the **"test"** sequences. May I ask that whether it is the same file (same noise var) to generate the **"train"** sequences?

Thanks!

**Comment by anchen1011** [comment]
Hi! Thanks for your interest! For detailed noise level, please refer to our publication [here](https://arxiv.org/abs/1711.09078). 

Meanwhile in short, it's definitely okay to use `add_noise_to_input` to generate "train" sequences.

**Comment by jiangzidong** [comment]
I see, thanks!
