### ISSUE TITLE
vimeo-90k

### ISSUE THREAD

**Issue by alterzero** [anchen1011/toflow#13]
Hi @anchen1011 ,

Thank you for your work.
I wonder, can I get original video clips from your Vimeo-90k dataset?
Or is it possible for you to create longer clips? for example 30-frame sequences

**Comment by anchen1011** [comment]
We do have the list of original video clips. For more information, feel free to send an email request to tfxue@mit.edu, and we will get back to you promptly.

**Comment by chriszhenghaochen** [comment]
Hi Dr Baian,

I tried to email the address you provide but said that tfxue is not in list of MIT, can you please provide another link or any other way to formally apply oringal 90K Vimeo data

Thank you very much for your work.

**Comment by tfxue** [comment]
The list of all videos we used are available here:

http://toflow.csail.mit.edu/index.html#original_video
