### ISSUE TITLE
Using ffmpeg to generate image sequence?

### ISSUE THREAD

**Issue by htzheng** [anchen1011/toflow#14]
Hello there, 

In the readme.md, the line `ffmpeg -i *.png -q 20 -vcodec jpeg2000 -format j2k name.mov ` can generate a video with extension MOV. 

I just wonder whether it is possible to directly generate a sequence of images.

Thank you!

**Comment by anchen1011** [comment]
We haven't found such a method yet. We currently use ffmpeg again to break video into frames.
