### ISSUE TITLE
runtime crash

### ISSUE THREAD

**Issue by owang** [anchen1011/toflow#2]
I'm trying to run this using this command: 

```th demo.lua -mode denoise -inpath ../data/example/noisy -outpath ./out```

And I'm getting this runtime error:

```
/torch/install/bin/luajit: ./main/loader.lua:27: argument 1 expected a 'string', got a 'nil'
stack traceback:
	./main/loader.lua:27: in function 'gen_path'
	demo.lua:47: in main chunk
```

**Comment by anchen1011** [comment]
Thanks for using our algorithm! There was a bug in loader.lua and it should be resolved now! 

I've tested it again with your command and it should work perfectly well with the current version. You can simply use `git pull` to update the code base.
