### ISSUE TITLE
add noise to input seems to have something wrong

### ISSUE THREAD

**Issue by cientgu** [anchen1011/toflow#21]
Hi, I found in your add_noise.m file line5,  why the noise is uint8(random('norm',0,25.5,h,w,3)) instead of random('norm',0,25.5,h,w,3)? is there anything wrong?

**Comment by tfxue** [comment]
This is an intended behavior. Most of testing images are 8-bit quantized and we want to also capture that in our training set.

**Comment by cientgu** [comment]
> This is an intended behavior. Most of testing images are 8-bit quantized and we want to also capture that in our training set.

but uint8 operation will make the noise to be always positive, it will not be a negative number, so it's actually not gaussian noise but "half gaussian noise".

**Comment by anchen1011** [comment]
Hi cientgu, you are right, and we have updated our paper, code, and dataset reflecting to this bug. Thank you!
