### ISSUE TITLE
Confusion on Image Transformation Module

### ISSUE THREAD

**Issue by jarvislkm** [anchen1011/toflow#23]
Hi, according to the paper section 4.3, STN layer is used for transformation estimation. Seems the implementation you use in this repo only support affine transformation? So does it mean in Fig2 the "warped input" is just an affine transformation of "Input frames"?

**Comment by tfxue** [comment]
Actually, we are using a full-resolution warping map, instead of the affine transformation. The implementation is at: src/stnbhwd/BilinearSamplerBHWD.cu, which is forked from original STN paper: https://arxiv.org/abs/1506.02025.
