### ISSUE TITLE
About the box down-sample kernel

### ISSUE THREAD

**Issue by LiangbinXie** [anchen1011/toflow#24]
Does the box down-sample kernel mentioned in your paper can be implemented by function imresize(img_hr, 1/up_scale, 'box'), I'm not sure whether they are same?

thanks~

**Comment by tfxue** [comment]
Sorry for the late reply. Yes, that is roughly how we generated downsampled images. Also, the model we released in this github is training on downsampled images using a cubic kernel, so it may perform worse on images downsampled by box kernels.

**Comment by LiangbinXie** [comment]
thanks~
