### ISSUE TITLE
Not all septuplets listed in "sep_testlist.txt" and "sep_trainlist.txt".

### ISSUE THREAD

**Issue by tlkvstepan** [anchen1011/toflow#26]
Hello Tianfan,
Thank you for sharing the dataset and code. I downloaded full septuplets dataset (training+test data) and found that "sep_testlist.txt" and "sep_trainlist.txt" contain only 72,436 setptuplets instead of  91,701. However, the folder with septuplets contains all  91,701 septuplets. Why not all septuplets appear in the  "sep_testlist.txt" and "sep_trainlist.txt"?

**Comment by anchen1011** [comment]
Some septuplets are filtered out due to quality reasons (the metrics are described in our paper) after we built the dataset, so I edited the list not the data.
