### ISSUE TITLE
demo.lua fails to run: cuDNN not found

### ISSUE THREAD

**Issue by xhuvom** [anchen1011/toflow#3]
The demo.lua not running after installing with Cuda and cuDNN. I had also installed 'luarocks install cudnn'
$ th demo.lua -mode denoise -inpath ../data/example/noisy 
==> initializing...	
/home/xhuv/torch/install/bin/luajit: /home/xhuv/torch/install/share/lua/5.1/trepl/init.lua:389: /home/xhuv/torch/install/share/lua/5.1/trepl/init.lua:389: /home/xhuv/torch/install/share/lua/5.1/trepl/init.lua:389: /home/xhuv/torch/install/share/lua/5.1/cudnn/ffi.lua:1603: 'libcudnn (R5) not found in library path.
Please install CuDNN from https://developer.nvidia.com/cuDNN
Then make sure files named as libcudnn.so.5 or libcudnn.5.dylib are placed in
your library load path (for example /usr/local/lib , or manually add a path to LD_LIBRARY_PATH)

Alternatively, set the path to libcudnn.so.5 or libcudnn.5.dylib
to the environment variable CUDNN_PATH and rerun torch.
For example: export CUDNN_PATH="/usr/local/cuda/lib64/libcudnn.so.5"

stack traceback:
	[C]: in function 'error'
	/home/xhuv/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	demo.lua:20: in main chunk
	[C]: in function 'dofile'
	...xhuv/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk

**Comment by anchen1011** [comment]
Thanks for trying our algorithm! It seems like some library is still missing, and it might be `cunn` or `cutorch`. 

Please try to install them with `luarocks install cunn` and `luarocks install cutorch` and run the command again. 

Please let us know if it still doesn't work or if there is further questions!

**Comment by xhuvom** [comment]
Sorry it doesn't help, the error still persists although I had installed cuda and cudnn as well as cunn and cutorch

**Comment by anchen1011** [comment]
Then to make sure you have cudnn installed correctly, please try to run command `th -lcudnn -e "print(cudnn.version)"`.

**Comment by anchen1011** [comment]
What's the version of cuda and cudnn that you are using? 
It seems like an environment setup problem then. 
You may run `th -lcudnn -e "print(cudnn.version)"` to make sure everything is correctly installed. 
If you are using cuda8 and cudnn5, the first thing you may try is the previous command doesn't give you a reasonable result should be `export CUDNN_ROOT="/usr/local/cuda-8.0/lib64/libcudnn.so.5" # you can maybe add this line into ~/.bashrc for future use`
Similar issue has been reported [here](https://github.com/soumith/cudnn.torch/issues/257).

**Comment by Jayhello** [comment]
as to me export CUDNN_PATH="/root/cudnn_5/lib64/libcudnn.so.5"

It is `CUDNN_PATH` not `CUDNN_ROOT`
