### ISSUE TITLE
What's dsr_imresize?

### ISSUE THREAD

**Issue by phoenix104104** [anchen1011/toflow#4]
Hi, 
In src/generate_testing_sample/blur_input.m, you use a custom function dsr_imresize.p (which is a binary file) to downsample and upsample images. But you mention that you use MATLAB imresize function to generate LR images in your paper Section 5. I check the output of MATLAB imresize and your dsr_imresize. There are some small differences between the LR images (from the same HR image). 

What's the difference between dsr_imresize and MATLAB imresize? Why not using MATLAB built-in imresize function?

**Comment by anchen1011** [comment]
Please use built-in imresize. Everything should be all coherent now!
