### ISSUE TITLE
Output at higher resolution

### ISSUE THREAD

**Issue by isVoid** [anchen1011/toflow#6]
Hi, I have several high resolution footages (4240x2382) that would like to be tested on this algorithm.

What are the options to get the same resolution as output?

**Comment by anchen1011** [comment]
Hi, I assume your question is about the automatic resizing of our algorithm? We currently only support 8x resolution (2382 / 8 = 297.75, thus it's not fully supported). An alternative is to use zero padding to make your input 4240 x 2384, run our algorithm, and then cut the padded part from the output. 

Hope this helps!

**Comment by letatanu** [comment]
> [https://github.com/anchen1011/toflow/issues/5](url)
This could solve your issue.
