### ISSUE TITLE
structure about the SPN net

### ISSUE THREAD

**Issue by JayMarx** [anchen1011/toflow#9]
@anchen1011 Hi, I am confused about the details of the SPN network. I referred to the spatial transformer network and tried to find the localisation net in your project but failed. Can you share your SPN structures? Thanks!

STN net
![stn](https://user-images.githubusercontent.com/22469594/43384796-a45a9fcc-9411-11e8-9854-625cd3dec880.png)

**Comment by anchen1011** [comment]
Hi, we are directly making use of STN. See our customized [WarpFlowNew](https://github.com/anchen1011/toflow/blob/master/src/util/nn/WarpFlowNew.lua) nn module for detail.

Please let us know if there is further confusion! Thanks for your interest in our project!

**Comment by anchen1011** [comment]
Closed due to inactivity. Feel free to reopen if there is further question~
